@extends('layouts.app')
@section('title','Branch Clients | CUPAD')
@section('content')
<div class="page-head"><h1>Branch Clients</h1><p>Active clients and portfolio balances for your branch.</p></div>
<div class="cards bm-client-cards"><div class="card"><span>Active Clients</span><strong id="totalClients">0</strong></div><div class="card"><span>Total Savings</span><strong id="totalSavings">₦0</strong></div><div class="card"><span>Outstanding Loans</span><strong id="totalLoans">₦0</strong></div></div>
<section class="panel"><div class="client-toolbar"><input id="search" placeholder="Search client, union or officer"><select id="sort"><option value="name_asc">Name</option><option value="savings_desc">Savings</option><option value="loan_desc">Loan balance</option><option value="officer_asc">Officer</option></select></div>
<div class="table-wrap"><table><thead><tr><th>Client</th><th>Union</th><th>Officer</th><th>Savings</th><th>Loan</th><th>Guarantor</th><th></th></tr></thead><tbody id="rows"></tbody></table></div><button id="more" class="bm-more">Load more</button></section>
<div id="modal" class="bm-modal" hidden><div class="bm-modal-card"><button class="close" onclick="closeModal()">×</button><h2 id="modalTitle"></h2><p id="modalOfficer" class="muted"></p><div class="modal-summary"><div><span>Savings</span><b id="mSavings">₦0</b></div><div><span>Loan</span><b id="mLoan">₦0</b></div></div><div id="history"></div></div></div>
<style>
.client-toolbar{display:flex;gap:10px;margin-bottom:15px}.client-toolbar input,.client-toolbar select{padding:11px;border:1px solid #d6dee8;border-radius:9px;background:#fff}.client-toolbar input{flex:1}.bm-client-cards{grid-template-columns:repeat(3,1fr)}.bm-more{margin-top:15px;width:100%;border:1px solid #dbe4ef;background:#f8fafc;border-radius:9px;padding:9px;cursor:pointer}.muted{color:#64748b;font-size:13px}.bm-modal{position:fixed;inset:0;background:rgba(15,23,42,.55);display:grid;place-items:center;padding:20px;z-index:100}.bm-modal-card{width:min(700px,100%);max-height:85vh;overflow:auto;background:#fff;border-radius:18px;padding:22px;position:relative}.close{position:absolute;right:15px;top:10px;border:0;background:none;font-size:28px;cursor:pointer}.modal-summary{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin:15px 0}.modal-summary div{padding:14px;border-radius:12px;background:#f5f8fc}.modal-summary span,.modal-summary b{display:block}.modal-summary span{color:#64748b;font-size:12px}.modal-summary b{font-size:20px;margin-top:4px}.history-row{display:flex;justify-content:space-between;gap:10px;padding:12px 0;border-bottom:1px solid #edf1f5}.history-row small{display:block;color:#64748b;margin-top:3px}@media(max-width:600px){.bm-client-cards{grid-template-columns:1fr}.client-toolbar{flex-direction:column}.bm-modal{padding:10px}}
</style>
<script>
let page=1;
function esc(s){return String(s||'').replace(/[&<>"']/g,function(m){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m];});}
async function load(reset){if(reset){page=1;document.getElementById('rows').innerHTML='';}const u='{{ route('bm.clients.data') }}?page='+page+'&search='+encodeURIComponent(document.getElementById('search').value)+'&sort='+document.getElementById('sort').value;const d=await (await fetch(u)).json();if(!d.success)return;document.getElementById('totalClients').textContent=Number(d.summary.total_clients).toLocaleString();document.getElementById('totalSavings').textContent='₦'+Number(d.summary.total_savings).toLocaleString();document.getElementById('totalLoans').textContent='₦'+Number(d.summary.total_loans).toLocaleString();d.clients.forEach(function(c){const tr=document.createElement('tr');tr.innerHTML='<td><strong>'+esc(c.name)+'</strong><small class="muted">'+esc(c.id)+'</small></td><td>'+esc(c.union||'Unassigned')+'</td><td>'+esc(c.officer_name)+'</td><td>₦'+Number(c.savings).toLocaleString()+'</td><td>₦'+Number(c.outstanding_loan).toLocaleString()+'</td><td>'+esc(c.guarantor_name)+'<small class="muted">'+esc(c.guarantor_phone)+'</small></td><td><button class="bm-more" type="button">History</button></td>';tr.querySelector('button').onclick=function(){historyOpen(c.id,c.name,c.officer_name)};document.getElementById('rows').appendChild(tr);});document.getElementById('more').style.display=d.pagination.has_more?'block':'none';if(d.pagination.has_more)page++;}
let timer;document.getElementById('search').oninput=function(){clearTimeout(timer);timer=setTimeout(function(){load(true)},300)};document.getElementById('sort').onchange=function(){load(true)};document.getElementById('more').onclick=function(){load(false)};load(true);
async function historyOpen(id,name,officer){document.getElementById('modal').hidden=false;document.getElementById('modalTitle').textContent=name;document.getElementById('modalOfficer').textContent=officer;const d=await (await fetch('{{ url('/bm/clients') }}/'+encodeURIComponent(id)+'/history')).json();if(!d.success)return;document.getElementById('mSavings').textContent='₦'+Number(d.summary.savings).toLocaleString();document.getElementById('mLoan').textContent='₦'+Number(d.summary.loan).toLocaleString();document.getElementById('history').innerHTML=d.history.map(function(x){return '<div class="history-row"><div><strong>'+esc(x.title)+'</strong><small>'+esc(x.description)+' · '+esc(x.date_formatted)+'</small></div><b>₦'+Number(x.amount).toLocaleString()+'</b></div>';}).join('')||'<div class="empty">No transactions found.</div>';}
function closeModal(){document.getElementById('modal').hidden=true;}
</script>
@endsection