@extends('layouts.app')
@section('title','CO Analytics')
@section('content')
<div class="max-w-7xl mx-auto px-4 py-6"><div class="flex flex-wrap justify-between items-end gap-3 mb-6"><div><h1 class="text-2xl font-extrabold">CO Analytics</h1><p class="text-sm text-gray-500">Portfolio-based performance and collection analysis</p></div><a href="{{ route('co.history') }}" class="px-4 py-2 rounded-xl border font-semibold">History</a></div>
<div class="flex flex-wrap gap-2 mb-5"><button class="preset px-4 py-2 rounded-xl bg-blue-600 text-white" data-p="month">This Month</button><button class="preset px-4 py-2 rounded-xl border" data-p="today">Today</button><button class="preset px-4 py-2 rounded-xl border" data-p="week">This Week</button><button class="preset px-4 py-2 rounded-xl border" data-p="last_month">Last Month</button></div>
<div id="cards" class="grid grid-cols-2 md:grid-cols-4 gap-3 mb-6"></div>
<div class="grid lg:grid-cols-3 gap-5"><div class="lg:col-span-2 rounded-2xl border bg-white dark:bg-slate-900 dark:border-slate-700 p-4"><h2 class="font-bold mb-3">Daily Activity</h2><canvas id="chart" height="110"></canvas></div><div class="rounded-2xl border bg-white dark:bg-slate-900 dark:border-slate-700 p-4"><h2 class="font-bold mb-3">Portfolio Totals</h2><div id="comp" class="space-y-3"></div></div></div>
<div class="mt-6 rounded-2xl border bg-white dark:bg-slate-900 dark:border-slate-700 overflow-x-auto"><table class="w-full text-sm"><thead class="bg-gray-50 dark:bg-slate-800"><tr><th class="p-3 text-left">Union</th><th class="p-3">Clients</th><th class="p-3">Savings</th><th class="p-3">Collections</th><th class="p-3">Disbursed</th><th class="p-3">Withdrawals</th><th class="p-3">Overdue</th></tr></thead><tbody id="unions"></tbody></table></div></div>
<script src="https://cdn.jsdelivr.net/npm/chart.js"></script><script>
let preset='month',chart;
const money=n=>'₦'+Number(n||0).toLocaleString('en-NG',{maximumFractionDigits:0});
document.querySelectorAll('.preset').forEach(b=>b.onclick=()=>{preset=b.dataset.p;load()});
async function load(){const d=await (await fetch('{{ route('co.analytics.data') }}?preset='+preset)).json();const m=d.metrics;const cards=[['Clients',m.total_clients],['Savings',money(m.total_savings)],['Net Savings',money(m.net_savings)],['Collections',money(m.total_collections)],['Disbursed',money(m.total_disbursements)],['Outstanding',money(m.total_outstanding)],['Active Loans',m.active_loans],['PAR Ratio',m.par_ratio+'%']];document.getElementById('cards').innerHTML=cards.map(x=>'<div class="rounded-2xl p-4 border bg-white dark:bg-slate-900 dark:border-slate-700"><div class="text-xs uppercase text-gray-500">'+x[0]+'</div><div class="text-xl font-extrabold mt-1">'+x[1]+'</div></div>').join('');document.getElementById('comp').innerHTML=Object.entries(d.chart_comp).map(x=>'<div><div class="flex justify-between text-sm font-semibold"><span>'+x[0]+'</span><span>'+money(x[1])+'</span></div><div class="h-2 bg-gray-100 dark:bg-slate-800 rounded-full mt-1"><div class="h-2 bg-blue-500 rounded-full" style="width:'+Math.min(100,(x[1]/Math.max(...Object.values(d.chart_comp),1))*100)+'%"></div></div></div>').join('');document.getElementById('unions').innerHTML=d.union_table.map(u=>'<tr class="border-t dark:border-slate-700"><td class="p-3 font-semibold">'+u.name+'</td><td class="p-3 text-center">'+u.clients+'</td><td class="p-3 text-center">'+money(u.total_savings)+'</td><td class="p-3 text-center">'+money(u.collections)+'</td><td class="p-3 text-center">'+money(u.disbursements)+'</td><td class="p-3 text-center">'+money(u.withdrawals)+'</td><td class="p-3 text-center">'+u.overdue_count+'</td></tr>').join('');const labels=d.chart_daily.map(x=>x.date);if(chart)chart.destroy();chart=new Chart(document.getElementById('chart'),{type:'line',data:{labels,datasets:[{label:'Savings',data:d.chart_daily.map(x=>x.savings)},{label:'Collections',data:d.chart_daily.map(x=>x.collections)}]},options:{responsive:true,plugins:{legend:{position:'bottom'}},scales:{y:{beginAtZero:true}}}})}load();
</script>
@endsection