@extends('layouts.app')
@section('title','My Clients')
@section('content')
<div class="max-w-7xl mx-auto px-4 py-6"><div class="flex justify-between items-end mb-6"><div><h1 class="text-2xl font-extrabold">Clients Portfolio</h1><p class="text-sm text-gray-500">Manage client profiles, savings and loan histories.</p></div></div>
<div class="grid md:grid-cols-3 gap-4 mb-6"><div class="p-5 rounded-2xl text-white bg-blue-600"><small>Total Clients</small><div id="tc" class="text-3xl font-extrabold">0</div></div><div class="p-5 rounded-2xl text-white bg-green-600"><small>Total Savings</small><div id="ts" class="text-3xl font-extrabold">₦0</div></div><div class="p-5 rounded-2xl text-white bg-red-500"><small>Outstanding Loans</small><div id="tl" class="text-3xl font-extrabold">₦0</div></div></div>
<div class="flex flex-col md:flex-row gap-3 mb-5"><input id="search" class="flex-1 p-3 rounded-xl border dark:bg-slate-800" placeholder="Search by name or union"><select id="status" class="p-3 rounded-xl border dark:bg-slate-800"><option value="all_active">All Active</option><option value="active_loan">Has Active Loan</option><option value="active_savings">Savings, No Loan</option><option value="inactive">Paid Off Loans</option></select><select id="sort" class="p-3 rounded-xl border dark:bg-slate-800"><option value="name_asc">Name</option><option value="savings_desc">Savings</option><option value="loan_desc">Outstanding Loan</option></select></div>
<div id="grid" class="grid md:grid-cols-2 lg:grid-cols-3 gap-4"></div><div class="flex justify-center gap-3 mt-6"><button id="prev" class="px-4 py-2 rounded-xl border">Previous</button><button id="next" class="px-4 py-2 rounded-xl bg-blue-600 text-white">Next</button></div></div>
<div id="modal" class="fixed inset-0 hidden items-end md:items-center justify-center bg-black/50 z-50"><div class="bg-white dark:bg-slate-900 w-full md:w-[560px] max-h-[90vh] overflow-auto rounded-t-3xl md:rounded-3xl p-5"><div class="flex justify-between"><div><h2 id="mn" class="text-xl font-bold"></h2><p id="ms" class="text-sm text-gray-500"></p></div><button onclick="closeM()" class="text-2xl">×</button></div><div id="mh" class="mt-5 space-y-3"></div></div></div>
<script>
let page=1;const money=n=>'₦'+Number(n||0).toLocaleString('en-NG',{maximumFractionDigits:0});const $=id=>document.getElementById(id);
async function load(p=1){page=Math.max(1,p);let q=new URLSearchParams({page,search:$('search').value,loan_status:$('status').value,sort:$('sort').value});let d=await(await fetch('{{ route('co.clients.data') }}?'+q)).json();if(!d.success)return;$('tc').textContent=d.summary.total_clients;$('ts').textContent=money(d.summary.total_savings);$('tl').textContent=money(d.summary.total_loans);$('grid').innerHTML=d.clients.map(c=>'<div class="rounded-2xl border bg-white dark:bg-slate-900 dark:border-slate-700 p-5 shadow-sm"><div class="flex justify-between gap-3"><div><h3 class="font-bold">'+esc(c.name)+'</h3><span class="text-xs text-gray-500">'+esc(c.union||'No Union')+'</span></div><span class="text-xs text-gray-400">'+esc(c.id)+'</span></div><div class="grid grid-cols-2 gap-2 my-4"><div class="p-3 rounded-xl bg-green-50 dark:bg-green-900/20"><small>Savings</small><div class="font-extrabold text-green-600">'+money(c.savings)+'</div></div><div class="p-3 rounded-xl bg-red-50 dark:bg-red-900/20"><small>Loan</small><div class="font-extrabold text-red-500">'+money(c.outstanding_loan)+'</div></div></div><div class="text-xs text-gray-500 mb-3">Phone: '+esc(c.phone||'N/A')+'<br>Guarantor: '+esc(c.guarantor_name||'N/A')+'</div><button onclick="historyClient('+JSON.stringify(c.id)+')" class="w-full py-2 rounded-xl bg-blue-600 text-white font-semibold">View History</button></div>').join('')||'<div class="col-span-full text-center p-10 text-gray-500">No clients found.</div>';$('prev').disabled=page===1;$('next').disabled=!d.pagination.has_more}
async function historyClient(id){let d=await(await fetch('{{ url('/co/clients') }}/'+encodeURIComponent(id)+'/history')).json();if(!d.success)return;$('mn').textContent=d.client_name;$('ms').textContent='Savings '+money(d.summary.savings)+' · Loan '+money(d.summary.loan);$('mh').innerHTML=d.history.map(x=>'<div class="flex gap-3 p-3 rounded-xl border dark:border-slate-700"><div class="w-9 h-9 rounded-lg bg-blue-50 text-blue-600 flex items-center justify-center"><i class="fas '+x.icon+'"></i></div><div class="flex-1"><b>'+esc(x.title)+'</b><div class="text-xs text-gray-500">'+esc(x.description)+' · '+esc(x.date_formatted)+'</div><div class="text-xs font-mono text-gray-400">'+esc(x.transaction_id)+'</div></div><strong>'+money(x.amount)+'</strong></div>').join('')||'<p class="text-gray-500">No history.</p>';$('modal').classList.remove('hidden');$('modal').classList.add('flex')}
function closeM(){$('modal').classList.add('hidden');$('modal').classList.remove('flex')}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
$('search').oninput=()=>load(1);$('status').onchange=()=>load(1);$('sort').onchange=()=>load(1);$('prev').onclick=()=>load(page-1);$('next').onclick=()=>load(page+1);load();
</script>
@endsection